# **Modul 4**
---
## **Integrasi Numerik dan Kuadratur Numerik** 



## 1. Metode Integrasi Numerik Simpson

Hasil integral dari suatu fungsi $f(x)$ pada dasarnya merupakan nilai luasan yang dibentuk oleh daerah di bawah kurva $f(x)$ yang dibatasi oleh sumbi $x$ dan garis pada batas bawah dan batasatas integral. Integrasi numerik merupakan suatu metode untuk mendekati hasil integral tersebut dengan sejumlah luasan kecil (_infinitesimal area_) dengan bentuk sederhana. Bentuk sederhana bagi luasan kecil tersebut dapat dipilih bentuk persegi, trapesium atau bentuk lengkung lainnya, yang dianggap lebih mendekati beberapa nilai fungsi pada beberapa titik.   

Salah satu metode integrasi numerik bagi fungsi $f(x)$ yang berbentuk sederhana namun memiliki keakuratan yang cukup tinggi adalah metode Simpson dengan ungkapan seperti berikut

$$\int_a^b\,f(x)dx\approx\frac{h}{3}\left[f(x_0)+4f(x_1)+2f(x_2)+\cdots+4f(x_{N-1})+f(x_N)\right]\tag{1a}$$

$$\int_a^b\,f(x)dx\approx\frac{h}{3}\left(f(x_0)+f(x_N)+4\sum_{i=1,3,\cdots}^{N-1}f(x_i)+2\sum_{i=2,4,\cdots}^{N-2}f(x_i)\right)\tag{1b}$$

Dalam ungkapan di atas, $N$ adalah sebarang bilangan genap, $x_0=a$, $x_N=b$,  ukuran langkah (_step size_) $h=\frac{b-a}{N}=\frac{x_N-x_0}{N}=x_i-x_{i-1}$ dan $x_i=x_0+ih$ dengan $i=1,2,\cdots,N$.

_Source-code_ bagi metode Simpson diberikan seperti contoh berikut. Untuk menunjukkan bahwa perhitungan integrasi numerik dengan metode Simpson dapat memberikan hasil dengan ketelitian tinggi maka dapat dicoba untuk bentuk fungsi $f(x)=\sin(x)$ pada berbagai nilai masukan $N$ atau $h$.

In [ ]:
from math import pi,sin,cos,sqrt
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
def fung(x):
    f = sin(x)
    return f

In [ ]:
def integsimpson(a,b,n):
    h=(b-a)/float(n)
    sumodd=0.0
    nhalf=int(n/2)
    for i in range(1, nhalf + 1):
        xodd = a + (2*i -1)*h
        sumodd += fung(xodd)
    sumeven=0.0
    for i in range(1, nhalf):
        xeven = a + 2*i*h
        sumeven += fung(xeven)
    integsimp = h*(fung(a) + 4.0*sumodd + 2.0*sumeven + fung(b))/3.0
    return integsimp

In [ ]:
integsimpson(0,pi/3,100)

0.5000000000334054

In [ ]:
cos(0)-cos(pi/3)

0.4999999999999999

## 2. Metode Kuadratur Numerik: _Gauss-Legendre_

Perhitungan numerik bagi nilai integral yang selama ini telah dikaji, sebagai contoh metode Simpson, adalah melalui proses diskretisasi peubah bebas pada titik-titik yang telah ditentukan $x_0, x_1, \cdots, x_N$. Secara umum nilai integral dari batas $a$ hingga $b$ dapat didekati oleh bentuk umum

$$\int_{x_0}^{x_N}f(x)dx\approx h\sum_{i=0}^N w_i f(x_i)\tag{2}$$,

dengan $h=x_i-x_{i-1}$ adalah ukuran langkah (_step size_) atau tingkat kehalusan diskretisasi, $w_i$ adalah nilai koefisien atau bobot fungsi  yang seperangkat nilainya dapat ditentukan oleh metode diskretisasi yang dipilih dan $x_0=a, x_N=b$. 

Sebagai contoh untuk metode Simpson maka $w_0=\frac{1}{3}, w_N=\frac{1}{3},$ $w_{2i-1}=\frac{4}{3}$ untuk $i=1,2,\cdots,\frac{N}{2}$ dan $w_{2i}=\frac{2}{3}$ untuk $i=1,2,\cdots,\frac{N}{2}-1$.

Nampak dari metode perhitungan numerik pers (2) bahwa pendekatan perhitungan nilai integral akan tidak berhasil apabila terjadi singularitas pada nilai fungsi di titik tertentu.

Dengan prosedur yang agak berbeda, metode kuadratur numerik adalah metode untuk mendekati nilai integral berdasarkan seperangkat nilai bobot $w_i$ dan titik $x_i$ yang ditentukan berdasarkan tingkat (_orde_) ketelitian yang akan dicapai, bukan berdasarkan proses diskretisasi. Dengan tambahan derajat kebebasan untuk memilih seperangkat titik $x_i$ maka 2 fitur yang dimiliki metode kuadratur, dibanding metode integrasi berdasar diskretisasi,  adalah

1. Singularitas dapat dihindari karena seperangkat titik $x_i$ tidak berada pada suatu titik yang menyebabkan nilai fungsi bernilai tak hingga.
2. Orde ketelitian lebih tinggi karena jumlah peubah bebas menjadi lebih banyak.

Sebagai gambaran terkait 2 fitur tersebut, tinjau ungkapan kuadratur numerik untuk kasus sedehana, yaitu berdasar evaluasi pada 2 titik $x_1$ dan $x_2$ yang berada pada interval $-1$ dan $1$, berikut

$$\int_{-1}^1 f(x)dx\approx w_1 f(x_1) + w_2 f(x_2)\tag{3}$$

Dalam ungkapan tersebut, sejumlah 4 nilai $w_1, w_2, x_1$ dan $x_2$ menjadi bebas untuk ditentukan. Salah satu cara untuk menentukan 4 nilai tersebut adalah dengan menyusun 4 persamaan yang menjamin bahwa pers (7) akan memberikan nilai eksak apabila $f(x)$ berbentuk polinomial hingga orde 3. 

* Untuk $f(x)=x^0=1$ maka pers (7) menjadi
$$\int_{-1}^1 1dx=2= w_1 x_1^0 + w_2 x_2^0=w_1+w_2\tag{4}$$

* Untuk $f(x)=x^1$ maka pers (7) menjadi
$$\int_{-1}^1 xdx=0= w_1 x_1 + w_2 x_2\tag{5}$$

* Untuk $f(x)=x^2$ maka pers (7) menjadi
$$\int_{-1}^1 x^2dx=\frac{2}{3}= w_1 x_1^2 + w_2 x_2^2\tag{6}$$

* Untuk $f(x)=x^3$ maka pers (7) menjadi
$$\int_{-1}^1 x^3dx=0= w_1 x_1^3 + w_2 x_2^3\tag{7}$$

Mudah ditunjukkan bahwa penyelsaian dari 4 persamaan serentak tersebut adalah

$w_1=1, w_2=1, x_1=-\frac{1}{\sqrt{3}}\approx=-0.577350269$ dan $x_2=\frac{1}{\sqrt{3}}\approx 0.577350269$.

Dengan pers (3) dan 4 nilai yang diperoleh tersebut maka metode kuadratur numerik pada 2 titik  berbentuk

$$\int_{-1}^1 f(x)dx\approx 1 f(-0.577350269) + 1 f(0.577350269)\tag{8}$$

---
Berikut adalah contoh penggunaan kuadratur numerik 2 titik untuk menentukan nilai integral dari $f(x)=2+x^2$


In [ ]:
c1=1.0
c2=1.0
x1=-0.577350269
x2=0.577350269
f1=2.0+x1**2
f2=2.0+x2**2
nilai_kuad=c1*f1+c2*f2
nilai_eksak=2.0*(1.0-(-1.0))+(1.0**3-(-1.0)**3)/3.0

In [ ]:
nilai_kuad

4.666666666228744

In [ ]:
nilai_eksak

4.666666666666667

Nampak bahwa perhitungan nilai integral berdasar metode kuadratur numerik dengan hanya menggunakan 2 titik dapat berhasil memberikan nilai yang cukup teliti. Ketelitian ini tentunya belum dapat diperoleh jika menggunakan metode Simpson dengan 2 titik yang sama. Ini merupakan salah satu fitur dari metode kuadratur numerik yang disinggung di atas.

### Ungkapan untuk Batas Integral yang Sebarang
Apabila batas integral adalah sebarang yaitu dari $y=a$ hingga $y=b$ maka bentuk kuadratur numerik dalam pers (3) dari $x=-1$ hingga $x=1$ dapat dilakukan pengaturan skala secara linear dalam bentuk

$$y=\frac{b-a}{2}x+\frac{b+a}{2}\tag{9}$$

Dengan pengaturan skala tersebut maka bentuk kuadratur numerik dalam pers (3) dapat digunakan dalam bentuk menjadi

$$\int_a^b f(y)dy\approx\frac{b-a}{2}\left[w_1 f\left(\frac{b-a}{2}x_1+\frac{b+a}{2}\right) + w_2 f\left(\frac{b-a}{2}x_2+\frac{b+a}{2}\right)\right]\tag{10}$$

Salah satu kendala bagi metode kuadratur numerik adalah perlunya pencarian seperangkat nilai $c_i$ dan $x_i$, saat $i=1,2,\cdots, N$, untuk cacah titik $N$ yang dipilih. Pada umumnya, pencarian nilai-nilai $c_i$ dan $x_i$ tersebut dapat dilakukan dengan melibatkan operasi pada fungsi khas (_special function_) berupa polinomial orthonormal  tertentu. 

Sebagai contoh, metode kuadratur numerik dengan ungkapan seperti diberikan oleh pers (3) merupakan bentuk khusus, yaitu saat cacah titik $N=2$, dari apa yang disebut sebagai metode kuadratur _Gauss-Legendre_ dengan bentuk umum

$$\int_{-1}^1 f(x)dx\approx \sum_{i=1}^n w_i f(x_i)\tag{11}$$

Nilai-nilai $x_i$ dapat diperoleh melalui akar-akar atau titik nol (_zeros_) dari polinomial _Legendre_ orde ke $n$, dengan lambang $P_n(x)$, sedangkan nilai-nilai $w_i$ diperoleh dengan melibatkan turunan ke 1 dari polinomial tersebut, yaitu melalui ungkapan

$$P_n(x_i)=0\tag{12a}$$

$$w_i=\frac{2}{(1-x_i^2)\left[P_n^{'}(x_i)\right]^2}\tag{12b}$$

Untuk beberapa titik yang tidak terlalu banyak, nilai-nilai $w_i$ dan $x_i$ bagi kuadratur _Gauss-Legendre_, seperti diberikan oleh pers (12), diberikan dalam bentuk Tabel seperti berikut ([Gaussian Kuadrature](https://en.wikipedia.org/wiki/Gaussian_quadrature))

Cacah titik $n$    | Bobot $w_i$      | Titik $x_i$
-|-|-
1|2|0
2|1|-0.577350...
 |1|0.577350...
3|0.555556...|-0.774597... 
|0.888889...|0
 |0.555556...|0.774597...
4|0.347855...|-0.861136...
 |0.652145...|-0.339981...
 |0.652145...|0.339981...
 |0.347855...|0.861136...
5|0.236927...|-0.90618...
 |0.478629...|-0.53846...
 |0.568889...|0
 |0.478629...|0.53846...
 |0.236927...|0.90618...

Sebagai gambaran terkait ketelitian metode kuadratur numerik, berikut akan ditunjukkan metode _Gauss-Legendre_ pada lima titik $n=5$ untuk menentukan nilai integral dari $f(x)=2+x^8$ dengan batas integral $a=0$ dan $b=3$.    


In [ ]:
def fung(x):
  f = 2.0 + x**8
  return f

def kuad_GL1(a,b):
    n = 5
    w = np.zeros(n+1)
    x = np.zeros(n+1)
    w[1] = 0.236927
    w[2] = 0.478629
    w[3] = 0.568889
    w[4] = 0.478629
    w[5] = 0.236927
    x[1] = -0.90618
    x[2] = -0.53846
    x[3] = 0.0
    x[4] = 0.53846
    x[5] = 0.90618
    sum = 0.0
    for i in range(1,n+1):
        y = (b-a)*x[i]/2.0 + (b+a)/2.0
        sum += w[i] * fung(y)
    kuad = (b-a) * sum/2.0
    return kuad

In [ ]:
kuad = kuad_GL1(0,3)

In [ ]:
kuad

2192.9742515366925

In [ ]:
eksak = 2.0 * 3.0 + 3.0**9/9

In [ ]:
eksak

2193.0

Selain disajikan dalam bentuk ungkapan seperti pers (12) atau bentuk Tabel, beberapa bahasa pemrograman atau paket matematika biasanya juga menyediakan _Library_ atau _Toolbox_ untuk membangkitkan nilai-nilai titik evaluasi fungsi ($x_i$) beserta nilai bobot terkait ($c_i$). Sebagai contoh, di dalam Python hal tersebut difasilitasi oleh _Library_ _Numpy_ atau _Scipy_ seperti berikut. 

In [ ]:
import numpy as np
import numpy.polynomial.legendre as geek

x,w = geek.leggauss(20)


In [ ]:
x

array([-0.9931286 , -0.96397193, -0.91223443, -0.83911697, -0.74633191,
       -0.63605368, -0.510867  , -0.37370609, -0.22778585, -0.07652652,
        0.07652652,  0.22778585,  0.37370609,  0.510867  ,  0.63605368,
        0.74633191,  0.83911697,  0.91223443,  0.96397193,  0.9931286 ])

In [ ]:
w

array([0.01761401, 0.04060143, 0.06267205, 0.08327674, 0.10193012,
       0.11819453, 0.13168864, 0.14209611, 0.14917299, 0.15275339,
       0.15275339, 0.14917299, 0.14209611, 0.13168864, 0.11819453,
       0.10193012, 0.08327674, 0.06267205, 0.04060143, 0.01761401])

In [ ]:
def fung(x):
  f = 2.0 + x**8
  return f

def kuad_GL(a,b):
    n = 30
    x,w = geek.leggauss(n) 
    sum = 0.0
    for i in range(n):
        y = (b-a)*x[i]/2.0 + (b+a)/2.0
        sum += w[i] * fung(y)
    kuad = (b-a) * sum/2.0
    return kuad

In [ ]:
kuad

2192.9742515366925

In [ ]:
import scipy
from scipy import special

x,w = scipy.special.roots_jacobi(5, 0.5, 0, mu=False)

In [ ]:
x

array([-0.91386262, -0.57376011, -0.0662439 ,  0.46107842,  0.85469297])

In [ ]:
w

array([0.30134625, 0.5589916 , 0.56181275, 0.35545735, 0.10801013])

### Bentuk Lain Metode Kuadratur Numerik

Metode kuadratur _Gauss-Legendre_ merupakan salah satu bentuk dari bentuk umum metode kuadratur yaitu

$$\int_{a}^b w(x)f(x)dx\approx \sum_{i=1}^n w_i f(x_i)\tag{13}$$

Ungkapan tersebut berlaku pada interval $[a,b]$ dan bentuk bobot $w(x)$ tertentu. Keadaan khusus saat $a=-1, b=1$ dan $w(x)=1$ maka pers (13) di atas merupakan bentuk dari metode kuadratur _Gauss-Legnedre_.

Interval $[a,b]$ dan bentuk fungsi bobot $w(x)$ akan terkait dengan fungsi khas dari polinomial orthonormal tertentu sehingga digunakan sebagai penamaan bagi metode kuadratur tersebut. Pemahaman terkait polinomial orthonormal tertentu tersebut akan berguna untuk mendapatkan nilai-nilai $x_i$ dan $w_i$ pada orde pendekatan tertentu.

Tabel berikut memberikan daftar dari beberapa bentuk metode kuadratur numerik yang banyak digunakan pada beberapa permasalahan perhitungan yang melibatkan integral tak layak.

Interval pada $[a,b]$| Bentuk fungsi bobot $w(x)$ |Polinomial Orthonormal |Nama Metode Kuadratur
--|-|-|- 
$[-1,1]$ |1|Polinomial _Legendre_ |_Gauss-Legendre_
$[-1,1]$ |$(1-x)^\alpha(1+x)^\beta$|Polinomial _Jacobi_ |_Gauss-Jacobi_
$[-1,1]$ |$\frac{1}{\sqrt{(1-x^2)}}$|Polinomial _Chebyshev_ jenis 1 |_Gauss-Chebyshev_
$[-1,1]$ |$\sqrt{(1-x^2)}$|Polinomial _Chebyshev_ jenis 2 |_Gauss-Chebyshev_
$[0,\infty]$ |$e^{-x}$|Polinomial _Laguerre_ jenis 2 |_Gauss-Laguerre_
$[-\infty,\infty]$ |$e^{-x^2}$|Polinomial _Hermite_ jenis 2 |_Gauss-Hermite_

## **Tugas**

Di dalam mekanika kuantum, ungkapan untuk memperoleh harga harap (_expectation value_) bagi besaran posisi kuadrat ($x^2$) pada sistem osilator harmonik pada tingkatan tenaga ke $10$ diberikan oleh ungkapan

$$<x^2>=\int_{-\infty}^\infty\psi_{10}^*(x)x^2\psi_{10}(x)\,dx$$

Dalam ungkapan di atas, fungsi *Hermite* pada orde ke $n$ yaitu $\psi_n(x)$ dikaitkan dengan polinomial *Hermite* orde ke $n$ yaitu $H_n(x)$ oleh bentuk yang sudah disampakan pad Modul ke 2 yaitu

$$\psi_n(x)=\sqrt{\frac{1}{2^n n!\sqrt{\pi}}}e^{-\tfrac{x^2}{2}}H_n(x)$$

Dengan demikian bentuk eksplisit harga harap (_expectation value_) bagi besaran posisi kuadrat adalah

$$<x^2>=\frac{1}{2^{10} 10!\sqrt{\pi}}\int_{-\infty}^\infty\,e^{-x^2}x^2H_{10}^2(x)\,dx\tag{14}$$

1. Metode Integrasi Numerik Simpson
> * Tentukan nilai harga harap (_expectation value_) bagi besaran posisi kuadrat seperti diberikan oleh pers (14) dengan menggunakan integrasi numerik Simpson. 
> * Sebagai pengganti bagi batas integral yang bernilai tak berhingga, maka dapat digunakan hasil plot fungsi *Hermite* orde ke 10 yang telah diperoleh pada Tugas di Modul ke 2. Dari plot tersebut maka dapat dilihat bahwa nilai fungsi *Hermite* orde ke 10 akan mengecil secara asimtotik pada nilai di sekitar $x\approx -8$ dan $x\approx 8$. Dengan demikian maka dapat diambil sebagai pendekatan bahwa batas integral dapat diambil pada $a=-8$ dan $b=8$.

2. Metode Kuadratur Numerik
> * Merujuk pada Tabel yang disampaikan di atas maka ungkapan pers (14) akan sesaui dengan bentuk metode kuadratur *Gauss-Hermite*. Tentukan nilai harga harap (_expectation value_) bagi besaran posisi kuadrat seperti diberikan oleh pers (14) dengan menggunakan integrasi kuadratur *Gauss-Hermite*.

Coba amati dan bandingkan hasil perhitungan dengan kedua metode di atas dan berikan komentar atas hasil tersebut.